/*
SGI - Sistema Gestion de Inventarios 
Vista Items
 */
package Vistas;

import Alertas.vistas.alertaInfo;
import Controladores.controlItems;
import Modelos.modeloCategorias;
import Modelos.modeloItems;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Coronado
 */
public class vistaItems extends javax.swing.JFrame {

    /**
     * Creates new form vistaItems
     */
    private int x;
    private int y;
    private String buscar = "";
    private String rol;

    public vistaItems(String rol) {
        this.setUndecorated(true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        setSize(1300, 680);
        this.setLocationRelativeTo(null);
        llenarVista();
        cargarTabla(buscar);
        this.rol = rol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Editar = new javax.swing.JMenuItem();
        lbl_codigo = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_descripcion = new javax.swing.JTextArea();
        box_categoria = new javax.swing.JComboBox<>();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_crearItem = new javax.swing.JButton();
        btn_pdf = new javax.swing.JButton();
        btn_excel = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Editar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Items");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1300, 680));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_codigo);
        lbl_codigo.setBounds(170, 215, 170, 30);

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nombre.setBorder(null);
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(170, 272, 170, 30);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane3.setMaximumSize(new java.awt.Dimension(166, 96));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(166, 96));

        area_descripcion.setColumns(20);
        area_descripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        area_descripcion.setLineWrap(true);
        area_descripcion.setRows(3);
        area_descripcion.setBorder(null);
        jScrollPane3.setViewportView(area_descripcion);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(170, 330, 180, 70);

        box_categoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(box_categoria);
        box_categoria.setBounds(166, 430, 185, 30);

        txt_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_buscar.setBorder(null);
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        getContentPane().add(txt_buscar);
        txt_buscar.setBounds(522, 58, 180, 30);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Item", "Descripcion", "Categoria", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(167, 125, 234));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 100, 850, 450);

        btn_crearItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/items/botonCrear1.png"))); // NOI18N
        btn_crearItem.setBorder(null);
        btn_crearItem.setBorderPainted(false);
        btn_crearItem.setContentAreaFilled(false);
        btn_crearItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_crearItem.setFocusPainted(false);
        btn_crearItem.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/items/botonCrear2.png"))); // NOI18N
        btn_crearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearItemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crearItem);
        btn_crearItem.setBounds(60, 580, 270, 43);

        btn_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/botonPDF1.png"))); // NOI18N
        btn_pdf.setBorder(null);
        btn_pdf.setBorderPainted(false);
        btn_pdf.setContentAreaFilled(false);
        btn_pdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pdf.setFocusPainted(false);
        btn_pdf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/botonPDF2.png"))); // NOI18N
        btn_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdfActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pdf);
        btn_pdf.setBounds(420, 560, 150, 70);

        btn_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL1.png"))); // NOI18N
        btn_excel.setBorder(null);
        btn_excel.setBorderPainted(false);
        btn_excel.setContentAreaFilled(false);
        btn_excel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excel.setFocusPainted(false);
        btn_excel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL2.png"))); // NOI18N
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excel);
        btn_excel.setBounds(570, 564, 160, 70);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(1270, 0, 30, 30);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/items/fondoItems.png"))); // NOI18N
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 1300, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        buscar = txt_buscar.getText();
        cargarTabla(buscar);
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void btn_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdfActionPerformed
        controlItems control = new controlItems();
        control.crearPDF();
    }//GEN-LAST:event_btn_pdfActionPerformed

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed
        controlItems control = new controlItems();
        control.crearXLS();
    }//GEN-LAST:event_btn_excelActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        if (!Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_SPACE) && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void btn_crearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearItemActionPerformed

        String id = lbl_codigo.getText();
        String nombre = txt_nombre.getText();
        String descripcion = area_descripcion.getText();
        String categoria = (String) box_categoria.getSelectedItem();

        if (nombre.equals("") && descripcion.equals("")) {
            alertaInfo alerta = new alertaInfo("Por favor verifique los datos.");
            alerta.setVisible(true);
        } else {
            modeloItems modelo = new modeloItems(id, nombre, descripcion, categoria);
            controlItems control = new controlItems();
            if (control.crearItem(modelo)) {
                txt_nombre.setText("");
                area_descripcion.setText("");
            }

        }
        llenarVista();
        cargarTabla(buscar);
    }//GEN-LAST:event_btn_crearItemActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        
        if (rol.equals("1")) {
            int fila = this.jTable1.getSelectedRow();
            lbl_codigo.setText((String) jTable1.getValueAt(fila, 0));
            txt_nombre.setText((String) jTable1.getValueAt(fila, 1));
            area_descripcion.setText((String) jTable1.getValueAt(fila, 2));
            box_categoria.setSelectedItem(jTable1.getValueAt(fila, 3));
        } else {
            alertaInfo alerta = new alertaInfo("No tiene asignado el rol de \nadministrador.");
            alerta.setVisible(true);
        }

    }//GEN-LAST:event_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String rol = null;
                new vistaItems(rol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Editar;
    private javax.swing.JTextArea area_descripcion;
    private javax.swing.JComboBox<String> box_categoria;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_crearItem;
    private javax.swing.JButton btn_excel;
    private javax.swing.JButton btn_pdf;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla(String buscar) {

        controlItems control = new controlItems();
        List<modeloItems> items = control.Consultar(buscar);
        DefaultTableModel tabla = new DefaultTableModel();
        this.jTable1.setModel(tabla);

        tabla.addColumn("Id");
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Item");
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Descripcion");
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        tabla.addColumn("Categoria");
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        tabla.addColumn("Disponible");
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(4).setResizable(false);

        for (modeloItems item : items) {
            Object[] fila = new Object[5];
            fila[0] = item.getId();
            fila[1] = item.getNombre();
            fila[2] = item.getDescripcion();
            fila[3] = item.getCategoria();
            fila[4] = item.getDisponible();
            tabla.addRow(fila);
        }
    }

    private void llenarVista() {
        controlItems control = new controlItems();
        lbl_codigo.setText(control.contar());

        List<modeloCategorias> categorias = control.categorias();
        box_categoria.removeAllItems();
        for (int i = 0; i < categorias.size(); i++) {
            box_categoria.addItem(categorias.get(i).getNombre());
        }

        txt_nombre.setText("");
        area_descripcion.setText("");

    }
}
