/*
SGI - Sistema Gestion de Inventarios 
Vista Menu
 */
package Vistas;

import Alertas.vistas.alertaInfo;
import Controladores.controlUsuarios;
import Modelos.modeloUsuarios;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Marco Coronado
 */
public class vistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     *
     */
    private int x;
    private int y;
    private String usuario;
    private String rol;

    public vistaMenu(String usuario, String rol) {

        this.setUndecorated(true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        setSize(950, 480);
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        this.rol = rol;
        llenarVista(usuario);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bienvenido = new javax.swing.JLabel();
        btn_items = new javax.swing.JButton();
        btn_entradas = new javax.swing.JButton();
        btn_salidas = new javax.swing.JButton();
        btn_empleados = new javax.swing.JButton();
        btn_usuarios = new javax.swing.JButton();
        btn_admin = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGI Inventarios");
        setUndecorated(true);
        setSize(new java.awt.Dimension(950, 480));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl_bienvenido.setFont(new java.awt.Font("Tahoma", 2, 22)); // NOI18N
        lbl_bienvenido.setText("Bienvenido, ");
        getContentPane().add(lbl_bienvenido);
        lbl_bienvenido.setBounds(176, 70, 620, 40);

        btn_items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/items1.png"))); // NOI18N
        btn_items.setBorder(null);
        btn_items.setBorderPainted(false);
        btn_items.setContentAreaFilled(false);
        btn_items.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_items.setFocusPainted(false);
        btn_items.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/items2.png"))); // NOI18N
        btn_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_itemsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_items);
        btn_items.setBounds(90, 200, 130, 120);

        btn_entradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/entradas1.png"))); // NOI18N
        btn_entradas.setBorder(null);
        btn_entradas.setBorderPainted(false);
        btn_entradas.setContentAreaFilled(false);
        btn_entradas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_entradas.setFocusPainted(false);
        btn_entradas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/entradas2.png"))); // NOI18N
        btn_entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entradasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entradas);
        btn_entradas.setBounds(250, 190, 110, 130);

        btn_salidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/salidas1.png"))); // NOI18N
        btn_salidas.setBorder(null);
        btn_salidas.setBorderPainted(false);
        btn_salidas.setContentAreaFilled(false);
        btn_salidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salidas.setFocusPainted(false);
        btn_salidas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/salidas2.png"))); // NOI18N
        btn_salidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salidasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salidas);
        btn_salidas.setBounds(403, 220, 100, 90);

        btn_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/empleados1.png"))); // NOI18N
        btn_empleados.setBorder(null);
        btn_empleados.setBorderPainted(false);
        btn_empleados.setContentAreaFilled(false);
        btn_empleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_empleados.setFocusPainted(false);
        btn_empleados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/empleados2.png"))); // NOI18N
        btn_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_empleados);
        btn_empleados.setBounds(560, 200, 110, 120);

        btn_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/usuarios1.png"))); // NOI18N
        btn_usuarios.setBorder(null);
        btn_usuarios.setBorderPainted(false);
        btn_usuarios.setContentAreaFilled(false);
        btn_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_usuarios.setFocusPainted(false);
        btn_usuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/usuarios2.png"))); // NOI18N
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuarios);
        btn_usuarios.setBounds(740, 200, 90, 130);

        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/admin1.png"))); // NOI18N
        btn_admin.setBorder(null);
        btn_admin.setBorderPainted(false);
        btn_admin.setContentAreaFilled(false);
        btn_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_admin.setFocusPainted(false);
        btn_admin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/admin2.png"))); // NOI18N
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_admin);
        btn_admin.setBounds(880, 5, 30, 40);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/botonCerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/botonCerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(915, 5, 30, 40);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/fondoMenu.png"))); // NOI18N
        lbl_fondo.setAlignmentY(0.0F);
        lbl_fondo.setMaximumSize(null);
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 950, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);

    }//GEN-LAST:event_formMouseDragged

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed

        System.exit(0);

    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed

        vistaEmpleados ventanaEmpleados = new vistaEmpleados(rol);
        ventanaEmpleados.setVisible(true);

    }//GEN-LAST:event_btn_empleadosActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed

        if (rol.equals("1")) {
            vistaConfiguracion ventConfiguracion = new vistaConfiguracion();
            ventConfiguracion.setVisible(true);
        } else {
            alertaInfo alerta = new alertaInfo("No tiene asignado el rol de \nadministrador.");
            alerta.setVisible(true);
        }

    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed

        vistaUsuarios ventanaUsuarios = new vistaUsuarios(rol);
        ventanaUsuarios.setVisible(true);

    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void btn_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_itemsActionPerformed

        vistaItems ventanaItems = new vistaItems(rol);
        ventanaItems.setVisible(true);

    }//GEN-LAST:event_btn_itemsActionPerformed

    private void btn_entradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entradasActionPerformed

        vistaEntradas ventanaEntradas = new vistaEntradas(usuario, rol);
        ventanaEntradas.setVisible(true);

    }//GEN-LAST:event_btn_entradasActionPerformed

    private void btn_salidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salidasActionPerformed

        vistaSalidas ventanaSalidas = new vistaSalidas(usuario, rol);
        ventanaSalidas.setVisible(true);

    }//GEN-LAST:event_btn_salidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String usuario = null;
                String rol = null;
                new vistaMenu(usuario, rol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_empleados;
    private javax.swing.JButton btn_entradas;
    private javax.swing.JButton btn_items;
    private javax.swing.JButton btn_salidas;
    private javax.swing.JButton btn_usuarios;
    private javax.swing.JLabel lbl_bienvenido;
    private javax.swing.JLabel lbl_fondo;
    // End of variables declaration//GEN-END:variables

    private void llenarVista(String usuario) {

        controlUsuarios control = new controlUsuarios();
        modeloUsuarios modelo = new modeloUsuarios();
        List<modeloUsuarios> usuarios = control.Consultar(usuario);
        lbl_bienvenido.setText("Bienvenido al Sistema Sr(a) " + usuarios.get(0).getEmp() + ".");

    }
}
