/*
SGI - Sistema Gestion de Inventarios 
Vista Configuracion
 */
package Vistas;

import Alertas.vistas.alertaInfo;
import Controladores.controlConfiguracion;
import Modelos.modeloCategorias;
import Modelos.modeloDocumentos;
import Modelos.modeloEmpresa;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Coronado
 */
public class vistaConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form vistaConfiguracion
     */
    private int x;
    private int y;

    public vistaConfiguracion() {
        this.setUndecorated(true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        setSize(1185, 693);
        this.setLocationRelativeTo(null);
        llenarEmpresas();
        llenarDocumentos();
        llenarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        lbl_codigoEmpresa = new javax.swing.JLabel();
        txt_nombreEmpresa = new javax.swing.JTextField();
        txt_nitEmpresa = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_empresas = new javax.swing.JTable();
        btn_empresa = new javax.swing.JButton();
        lbl_codigoDocumento = new javax.swing.JLabel();
        txt_nombreDocumento = new javax.swing.JTextField();
        txt_prefijoDocumento = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_documentos = new javax.swing.JTable();
        btn_documento = new javax.swing.JButton();
        txt_nombreCategoria = new javax.swing.JTextField();
        lbl_codigoCategoria = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_categorias = new javax.swing.JTable();
        btn_categoria = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Editar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        jMenuItem3.setText("Editar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGI Configuración");
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl_codigoEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_codigoEmpresa);
        lbl_codigoEmpresa.setBounds(176, 300, 170, 30);

        txt_nombreEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nombreEmpresa.setBorder(null);
        getContentPane().add(txt_nombreEmpresa);
        txt_nombreEmpresa.setBounds(176, 355, 170, 30);

        txt_nitEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nitEmpresa.setBorder(null);
        txt_nitEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nitEmpresaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nitEmpresa);
        txt_nitEmpresa.setBounds(176, 409, 170, 30);

        tbl_empresas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_empresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Razon Social", "Nit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_empresas.setToolTipText("");
        tbl_empresas.setComponentPopupMenu(jPopupMenu1);
        tbl_empresas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_empresas.setFocusable(false);
        tbl_empresas.setRowHeight(25);
        tbl_empresas.setSelectionBackground(new java.awt.Color(167, 125, 234));
        jScrollPane5.setViewportView(tbl_empresas);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(40, 460, 320, 126);

        btn_empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion/btn_Actualizar1.png"))); // NOI18N
        btn_empresa.setBorder(null);
        btn_empresa.setBorderPainted(false);
        btn_empresa.setContentAreaFilled(false);
        btn_empresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_empresa.setFocusPainted(false);
        btn_empresa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion/btn_Actualizar2.png"))); // NOI18N
        btn_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empresaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_empresa);
        btn_empresa.setBounds(70, 600, 270, 42);

        lbl_codigoDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_codigoDocumento);
        lbl_codigoDocumento.setBounds(567, 298, 170, 30);

        txt_nombreDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nombreDocumento.setBorder(null);
        txt_nombreDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreDocumentoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombreDocumento);
        txt_nombreDocumento.setBounds(567, 353, 170, 30);

        txt_prefijoDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_prefijoDocumento.setBorder(null);
        txt_prefijoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prefijoDocumentoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_prefijoDocumento);
        txt_prefijoDocumento.setBounds(567, 407, 170, 30);

        tbl_documentos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_documentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Documento", "Prefijo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_documentos.setComponentPopupMenu(jPopupMenu2);
        tbl_documentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_documentos.setFocusable(false);
        tbl_documentos.setRowHeight(25);
        tbl_documentos.setSelectionBackground(new java.awt.Color(167, 125, 234));
        tbl_documentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_documentosMouseReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tbl_documentos);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(430, 460, 320, 126);

        btn_documento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion/btn_Documento1.png"))); // NOI18N
        btn_documento.setBorder(null);
        btn_documento.setBorderPainted(false);
        btn_documento.setContentAreaFilled(false);
        btn_documento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_documento.setFocusPainted(false);
        btn_documento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion/btn_Documento2.png"))); // NOI18N
        btn_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_documentoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_documento);
        btn_documento.setBounds(460, 600, 270, 42);

        txt_nombreCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nombreCategoria.setBorder(null);
        txt_nombreCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreCategoriaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombreCategoria);
        txt_nombreCategoria.setBounds(960, 353, 170, 30);

        lbl_codigoCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_codigoCategoria);
        lbl_codigoCategoria.setBounds(960, 298, 170, 30);

        tbl_categorias = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_categorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Categoría"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_categorias.setComponentPopupMenu(jPopupMenu3);
        tbl_categorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_categorias.setFocusable(false);
        tbl_categorias.setRowHeight(25);
        tbl_categorias.setSelectionBackground(new java.awt.Color(167, 125, 234));
        tbl_categorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_categoriasMouseReleased(evt);
            }
        });
        jScrollPane7.setViewportView(tbl_categorias);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(820, 409, 320, 176);

        btn_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion/btn_Categoria1.png"))); // NOI18N
        btn_categoria.setBorder(null);
        btn_categoria.setBorderPainted(false);
        btn_categoria.setContentAreaFilled(false);
        btn_categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_categoria.setFocusPainted(false);
        btn_categoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion/btn_Categoria2.png"))); // NOI18N
        btn_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_categoria);
        btn_categoria.setBounds(860, 600, 270, 42);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(1155, 0, 30, 30);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion/fondoConfiguracion.png"))); // NOI18N
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 1195, 693);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed

        dispose();

    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void txt_nitEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nitEmpresaKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nitEmpresaKeyTyped

    private void txt_nombreDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreDocumentoKeyTyped

        if (!Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
            evt.consume();
        }

    }//GEN-LAST:event_txt_nombreDocumentoKeyTyped

    private void txt_prefijoDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prefijoDocumentoKeyTyped

        if (!Character.isLetter(evt.getKeyChar())) {
            if (txt_prefijoDocumento.getText().length() < 2) {
                System.out.println("evt = " + txt_prefijoDocumento.getText().length() + " 2");
                evt.consume();

            }
        }


    }//GEN-LAST:event_txt_prefijoDocumentoKeyTyped

    private void txt_nombreCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreCategoriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreCategoriaKeyTyped

    private void tbl_documentosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_documentosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_documentosMouseReleased

    private void tbl_categoriasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_categoriasMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_categoriasMouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        int fila = this.tbl_empresas.getSelectedRow();
        lbl_codigoEmpresa.setText((String) tbl_empresas.getValueAt(fila, 0));
        txt_nombreEmpresa.setText((String) tbl_empresas.getValueAt(fila, 1));
        txt_nitEmpresa.setText((String) tbl_empresas.getValueAt(fila, 2));

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        int fila = this.tbl_documentos.getSelectedRow();
        lbl_codigoDocumento.setText((String) tbl_documentos.getValueAt(fila, 0));
        txt_nombreDocumento.setText((String) tbl_documentos.getValueAt(fila, 1));
        txt_prefijoDocumento.setText((String) tbl_documentos.getValueAt(fila, 2));

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        int fila = this.tbl_categorias.getSelectedRow();
        lbl_codigoCategoria.setText((String) tbl_categorias.getValueAt(fila, 0));
        txt_nombreCategoria.setText((String) tbl_categorias.getValueAt(fila, 1));

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empresaActionPerformed

        String nombre = txt_nombreEmpresa.getText();
        String nit = txt_nitEmpresa.getText();

        if (nombre.equals("") || nit.equals("")) {
            alertaInfo alerta = new alertaInfo("Verifique los datos de la \nempresa");
            alerta.setVisible(true);
        } else {
            controlConfiguracion control = new controlConfiguracion();
            control.actualizarEmpresa(nombre, nit);
            llenarEmpresas();
        }

    }//GEN-LAST:event_btn_empresaActionPerformed

    private void btn_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoriaActionPerformed

        String codigo = lbl_codigoCategoria.getText();
        String nombre = txt_nombreCategoria.getText();
        
        if (nombre.equals("") || codigo.equals("")) {
            alertaInfo alerta = new alertaInfo("Verifique los datos de la \ncategoría");
            alerta.setVisible(true);
        } else {
            controlConfiguracion control = new controlConfiguracion();
            control.crearCategoria(codigo, nombre);
            llenarCategorias();
        }

    }//GEN-LAST:event_btn_categoriaActionPerformed

    private void btn_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_documentoActionPerformed

        String codigo = lbl_codigoDocumento.getText();
        String nombre = txt_nombreDocumento.getText();
        String prefijo = txt_prefijoDocumento.getText();
        
        if (nombre.equals("") || codigo.equals("") || prefijo.equals("")) {
            alertaInfo alerta = new alertaInfo("Verifique los datos del tipo \ndocumento");
            alerta.setVisible(true);
        } else {
            controlConfiguracion control = new controlConfiguracion();
            control.crearDocumento(codigo, nombre, prefijo);
            llenarDocumentos();
        }
        
    }//GEN-LAST:event_btn_documentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_categoria;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_documento;
    private javax.swing.JButton btn_empresa;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbl_codigoCategoria;
    private javax.swing.JLabel lbl_codigoDocumento;
    private javax.swing.JLabel lbl_codigoEmpresa;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JTable tbl_categorias;
    private javax.swing.JTable tbl_documentos;
    private javax.swing.JTable tbl_empresas;
    private javax.swing.JTextField txt_nitEmpresa;
    private javax.swing.JTextField txt_nombreCategoria;
    private javax.swing.JTextField txt_nombreDocumento;
    private javax.swing.JTextField txt_nombreEmpresa;
    private javax.swing.JTextField txt_prefijoDocumento;
    // End of variables declaration//GEN-END:variables

    private void llenarEmpresas() {

        lbl_codigoEmpresa.setText("");
        txt_nombreEmpresa.setText("");
        txt_nitEmpresa.setText("");

        controlConfiguracion control = new controlConfiguracion();
        List<modeloEmpresa> listaEmpresa = control.consultarEmpresas();
        DefaultTableModel tabla = new DefaultTableModel();
        this.tbl_empresas.setModel(tabla);

        tabla.addColumn("Código");
        tbl_empresas.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbl_empresas.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Razon Social");
        tbl_empresas.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_empresas.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Nit");
        tbl_empresas.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbl_empresas.getColumnModel().getColumn(2).setResizable(false);

        for (modeloEmpresa empresa : listaEmpresa) {
            Object[] fila = new Object[3];
            fila[0] = empresa.getId();
            fila[1] = empresa.getNombre();
            fila[2] = empresa.getNit();
            tabla.addRow(fila);
        }
    }

    private void llenarDocumentos() {

        controlConfiguracion control = new controlConfiguracion();
        List<modeloDocumentos> listaDocumentos = control.consultarDocumentos();
        DefaultTableModel tabla = new DefaultTableModel();
        this.tbl_documentos.setModel(tabla);

        tabla.addColumn("Código");
        tbl_documentos.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbl_documentos.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Documento");
        tbl_documentos.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_documentos.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Prefijo");
        tbl_documentos.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbl_documentos.getColumnModel().getColumn(2).setResizable(false);

        for (modeloDocumentos documento : listaDocumentos) {
            Object[] fila = new Object[3];
            fila[0] = documento.getId();
            fila[1] = documento.getTipo();
            fila[2] = documento.getPrefijo();
            tabla.addRow(fila);
        }

        lbl_codigoDocumento.setText(control.contarDocumentos());
        txt_nombreDocumento.setText("");
        txt_prefijoDocumento.setText("");

    }

    private void llenarCategorias() {

        controlConfiguracion control = new controlConfiguracion();
        List<modeloCategorias> listaCategorias = control.consultarCategorias();
        DefaultTableModel tabla = new DefaultTableModel();
        this.tbl_categorias.setModel(tabla);

        tabla.addColumn("Código");
        tbl_categorias.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbl_categorias.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Categoría");
        tbl_categorias.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_categorias.getColumnModel().getColumn(1).setResizable(false);

        for (modeloCategorias categoria : listaCategorias) {
            Object[] fila = new Object[2];
            fila[0] = categoria.getId();
            fila[1] = categoria.getNombre();
            tabla.addRow(fila);
        }

        lbl_codigoCategoria.setText(control.contarCategorias());
        txt_nombreCategoria.setText("");
    }
}
