/*
SGI - Sistema Gestion de Inventarios 
Vista Salidas
 */
package Vistas;

import Alertas.vistas.alertaInfo;
import Controladores.controlItems;
import Controladores.controlSalidas;
import Modelos.modeloEmpleados;
import Modelos.modeloItems;
import Modelos.modeloSalidas;
import java.awt.MouseInfo;
import java.awt.Point;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Coronado
 */
public class vistaSalidas extends javax.swing.JFrame {

    /**
     * Creates new form vistaEntradas
     */
    private int x;
    private int y;
    private String buscar = "";
    private String rol;
    List<modeloSalidas> listaSalidas = new ArrayList<modeloSalidas>();

    public vistaSalidas(String usuario, String rol) {
        this.setUndecorated(true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        setSize(1300, 680);
        this.setLocationRelativeTo(null);
        llenarVista(usuario);
        cargarTabla(buscar);
        this.rol = rol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_items = new javax.swing.JTable();
        txt_codigo = new javax.swing.JTextField();
        txt_item = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        btn_anadirItem = new javax.swing.JButton();
        lbl_salida = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        box_empleado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_salidas = new javax.swing.JTable();
        btn_crearSalida = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        btn_excel = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salidas");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1300, 680));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        txt_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_buscar.setBorder(null);
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        getContentPane().add(txt_buscar);
        txt_buscar.setBounds(176, 226, 170, 30);

        tbl_items = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Item", "Descripcion", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_items.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_items.setFocusable(false);
        tbl_items.setRowHeight(25);
        tbl_items.setSelectionBackground(new java.awt.Color(167, 125, 234));
        tbl_items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_itemsMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_items);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(40, 280, 320, 126);

        txt_codigo.setEditable(false);
        txt_codigo.setBackground(new java.awt.Color(255, 255, 255));
        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_codigo.setBorder(null);
        getContentPane().add(txt_codigo);
        txt_codigo.setBounds(176, 431, 170, 30);

        txt_item.setEditable(false);
        txt_item.setBackground(new java.awt.Color(255, 255, 255));
        txt_item.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_item.setBorder(null);
        getContentPane().add(txt_item);
        txt_item.setBounds(176, 483, 170, 30);

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cantidad.setBorder(null);
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cantidad);
        txt_cantidad.setBounds(176, 533, 170, 30);

        btn_anadirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entradas/btnAddItem1.png"))); // NOI18N
        btn_anadirItem.setBorder(null);
        btn_anadirItem.setBorderPainted(false);
        btn_anadirItem.setContentAreaFilled(false);
        btn_anadirItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_anadirItem.setFocusPainted(false);
        btn_anadirItem.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entradas/btnAddItem2.png"))); // NOI18N
        btn_anadirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirItemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anadirItem);
        btn_anadirItem.setBounds(60, 580, 270, 43);

        lbl_salida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_salida);
        lbl_salida.setBounds(510, 58, 70, 30);

        lbl_fecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_fecha);
        lbl_fecha.setBounds(681, 58, 70, 30);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_usuario);
        lbl_usuario.setBounds(862, 58, 120, 30);

        box_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(box_empleado);
        box_empleado.setBounds(1110, 58, 160, 30);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbl_salidas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_salidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Item", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_salidas.setComponentPopupMenu(jPopupMenu1);
        tbl_salidas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_salidas.setFocusable(false);
        tbl_salidas.setRowHeight(25);
        tbl_salidas.setSelectionBackground(new java.awt.Color(167, 125, 234));
        jScrollPane2.setViewportView(tbl_salidas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(420, 110, 855, 450);

        btn_crearSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salidas/btn_CrearSalida1.png"))); // NOI18N
        btn_crearSalida.setBorder(null);
        btn_crearSalida.setBorderPainted(false);
        btn_crearSalida.setContentAreaFilled(false);
        btn_crearSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_crearSalida.setFocusPainted(false);
        btn_crearSalida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salidas/btn_CrearSalida2.png"))); // NOI18N
        btn_crearSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crearSalida);
        btn_crearSalida.setBounds(1008, 580, 270, 42);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(1270, 0, 30, 30);

        btn_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL1.png"))); // NOI18N
        btn_excel.setBorder(null);
        btn_excel.setBorderPainted(false);
        btn_excel.setContentAreaFilled(false);
        btn_excel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excel.setFocusPainted(false);
        btn_excel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL2.png"))); // NOI18N
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excel);
        btn_excel.setBounds(420, 564, 160, 70);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salidas/fondoSalidas.png"))); // NOI18N
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 1300, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed

        dispose();

    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_anadirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirItemActionPerformed

        String id = txt_codigo.getText();
        String item = txt_item.getText();
        String cantidad = txt_cantidad.getText();
        String usuario = lbl_usuario.getText();

        int fila = this.tbl_items.getSelectedRow();
        String disponible = (String) tbl_items.getValueAt(fila, 3);

        if (Integer.parseInt(cantidad) <= 0) {
            alertaInfo alerta = new alertaInfo("Verifique los datos \n"
                    + "la salida no puede ser 0");
            alerta.setVisible(true);
        } else if (Integer.parseInt(cantidad) > Integer.parseInt(disponible)) {
            alertaInfo alerta = new alertaInfo("La salida no puede ser mayor al disponible");
            alerta.setVisible(true);
        } else {
            modeloSalidas salidas = new modeloSalidas(id, item, cantidad);
            listaSalidas.add(salidas);

            cargarTablaSalidas();
            llenarVista(usuario);
        }

    }//GEN-LAST:event_btn_anadirItemActionPerformed

    private void btn_crearSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearSalidaActionPerformed

        controlSalidas control = new controlSalidas();
        modeloSalidas modelo = new modeloSalidas();
        String empleado = (String) box_empleado.getSelectedItem();

        control.crearDocumentoSalida(lbl_salida.getText(), lbl_usuario.getText(), empleado);
        control.crearSalidas(lbl_salida.getText(), listaSalidas);
        control.crearPDF(lbl_salida.getText(), lbl_usuario.getText(), listaSalidas, empleado);
        listaSalidas.clear();
        listaSalidas.removeAll(listaSalidas);
        llenarVista(lbl_usuario.getText());
        cargarTabla(buscar);
        modelo = null;
        System.gc();
        cargarTablaSalidas();

    }//GEN-LAST:event_btn_crearSalidaActionPerformed

    private void tbl_itemsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_itemsMouseReleased

        int fila = this.tbl_items.getSelectedRow();
        txt_codigo.setText((String) tbl_items.getValueAt(fila, 0));
        txt_item.setText((String) tbl_items.getValueAt(fila, 1));

    }//GEN-LAST:event_tbl_itemsMouseReleased

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased

        buscar = txt_buscar.getText();
        cargarTabla(buscar);

    }//GEN-LAST:event_txt_buscarKeyReleased

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped

        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        listaSalidas.remove(tbl_salidas.getSelectedRow());
        cargarTablaSalidas();


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed
        
        controlSalidas control = new controlSalidas();
        control.crearXLS();
        
    }//GEN-LAST:event_btn_excelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String usuario = null;
                String rol = null;
                new vistaSalidas(usuario, rol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_empleado;
    private javax.swing.JButton btn_anadirItem;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_crearSalida;
    private javax.swing.JButton btn_excel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_salida;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable tbl_items;
    private javax.swing.JTable tbl_salidas;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_item;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla(String buscar) {

        controlItems control = new controlItems();
        List<modeloItems> items = control.Consultar(buscar);
        DefaultTableModel tabla = new DefaultTableModel();
        this.tbl_items.setModel(tabla);

        tabla.addColumn("Id");
        tbl_items.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbl_items.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Item");
        tbl_items.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_items.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Descripcion");
        tbl_items.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbl_items.getColumnModel().getColumn(2).setResizable(false);

        tabla.addColumn("Disponible");
        tbl_items.getColumnModel().getColumn(3).setPreferredWidth(30);
        tbl_items.getColumnModel().getColumn(3).setResizable(false);

        for (modeloItems item : items) {
            Object[] fila = new Object[4];
            fila[0] = item.getId();
            fila[1] = item.getNombre();
            fila[2] = item.getDescripcion();
            fila[3] = item.getDisponible();
            tabla.addRow(fila);
        }
    }

    private void llenarVista(String usuario) {

        controlSalidas control = new controlSalidas();
        lbl_salida.setText(control.contar());

        DateTimeFormatter fecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        lbl_fecha.setText(fecha.format(LocalDateTime.now()));

        lbl_usuario.setText(usuario);
        txt_codigo.setText("");
        txt_item.setText("");
        txt_buscar.setText("");
        txt_cantidad.setText("0");

        List<modeloEmpleados> empleados = control.empleados();
        box_empleado.removeAllItems();
        for (int i = 0; i < empleados.size(); i++) {
            box_empleado.addItem(empleados.get(i).getNombre());
        }

    }

    private void cargarTablaSalidas() {

        DefaultTableModel tabla = new DefaultTableModel();
        this.tbl_salidas.setModel(tabla);

        tabla.addColumn("Id");
        tbl_salidas.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbl_salidas.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Item");
        tbl_salidas.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_salidas.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Cantidad");
        tbl_salidas.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbl_salidas.getColumnModel().getColumn(2).setResizable(false);

        for (modeloSalidas salida : listaSalidas) {
            Object[] fila = new Object[3];
            fila[0] = salida.getId();
            fila[1] = salida.getInventario();
            fila[2] = salida.getCantidad();
            tabla.addRow(fila);
        }
    }
}
