/*
SGI - Sistema Gestion de Inventarios 
Vista Empleados
 */
package Vistas;

import Alertas.vistas.alertaInfo;
import Controladores.controlEmpleados;
import Modelos.modeloDocumentos;
import Modelos.modeloEmpleados;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Coronado
 */
public class vistaEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form vistaEmpleados
     */
    private int x;
    private int y;
    private String buscar = "";
    private String rol;

    public vistaEmpleados(String rol) {

        this.setUndecorated(true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        setSize(1300, 680);
        this.setLocationRelativeTo(null);
        llenarVista();
        cargarTabla(buscar);
        this.rol = rol;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        lbl_codigo = new javax.swing.JLabel();
        lbl_empresa = new javax.swing.JLabel();
        box_tipoDoc = new javax.swing.JComboBox<>();
        txt_numDocumento = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        box_genero = new javax.swing.JComboBox<>();
        txt_correo = new javax.swing.JTextField();
        btn_crearEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_cerrar = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        btn_pdf = new javax.swing.JButton();
        btn_excel = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_codigo);
        lbl_codigo.setBounds(176, 209, 170, 30);

        lbl_empresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_empresa);
        lbl_empresa.setBounds(176, 260, 170, 30);

        getContentPane().add(box_tipoDoc);
        box_tipoDoc.setBounds(165, 313, 192, 30);

        txt_numDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_numDocumento.setBorder(null);
        txt_numDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numDocumentoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_numDocumento);
        txt_numDocumento.setBounds(176, 364, 170, 30);

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nombre.setBorder(null);
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(176, 416, 170, 30);

        box_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        getContentPane().add(box_genero);
        box_genero.setBounds(165, 464, 192, 30);

        txt_correo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_correo.setBorder(null);
        getContentPane().add(txt_correo);
        txt_correo.setBounds(176, 514, 170, 30);

        btn_crearEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados/botonCrear1.png"))); // NOI18N
        btn_crearEmpleado.setBorder(null);
        btn_crearEmpleado.setBorderPainted(false);
        btn_crearEmpleado.setContentAreaFilled(false);
        btn_crearEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_crearEmpleado.setFocusPainted(false);
        btn_crearEmpleado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados/botonCrear2.png"))); // NOI18N
        btn_crearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crearEmpleado);
        btn_crearEmpleado.setBounds(60, 580, 270, 43);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Empresa", "Tipo de Documento", "Documento", "Nombre", "Genero", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(167, 125, 234));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 100, 850, 450);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(1270, 0, 30, 30);

        txt_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_buscar.setBorder(null);
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        getContentPane().add(txt_buscar);
        txt_buscar.setBounds(522, 58, 180, 30);

        btn_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/botonPDF1.png"))); // NOI18N
        btn_pdf.setBorder(null);
        btn_pdf.setBorderPainted(false);
        btn_pdf.setContentAreaFilled(false);
        btn_pdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pdf.setFocusPainted(false);
        btn_pdf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/botonPDF2.png"))); // NOI18N
        btn_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdfActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pdf);
        btn_pdf.setBounds(420, 560, 150, 70);

        btn_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL1.png"))); // NOI18N
        btn_excel.setBorder(null);
        btn_excel.setBorderPainted(false);
        btn_excel.setContentAreaFilled(false);
        btn_excel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excel.setFocusPainted(false);
        btn_excel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL2.png"))); // NOI18N
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excel);
        btn_excel.setBounds(570, 564, 160, 70);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados/fondoEmpleados.png"))); // NOI18N
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 1300, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed

        dispose();

    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_crearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearEmpleadoActionPerformed

        String id = lbl_codigo.getText();
        String empresa = "1";
        String tipoDoc = (String) box_tipoDoc.getSelectedItem();
        String documento = txt_numDocumento.getText();
        String nombre = txt_nombre.getText();
        String genero = (String) box_genero.getSelectedItem();
        String correo = txt_correo.getText();

        if (documento.equals("") || nombre.equals("")) {
            alertaInfo alerta = new alertaInfo("Por favor verifique los datos.");
            alerta.setVisible(true);
        } else if (verificarCorreo(correo) == false) {
            alertaInfo alerta = new alertaInfo("Correo invalido.");
            alerta.setVisible(true);
        } else {
            modeloEmpleados modelo = new modeloEmpleados(id, empresa, tipoDoc, documento, nombre, genero, correo);
            controlEmpleados control = new controlEmpleados();
            if (control.crearEmpleado(modelo)) {
                txt_numDocumento.setText("");
                txt_nombre.setText("");
                txt_correo.setText("");
                llenarVista();
                cargarTabla(buscar);
            }
        }


    }//GEN-LAST:event_btn_crearEmpleadoActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        buscar = txt_buscar.getText();
        cargarTabla(buscar);
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void btn_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdfActionPerformed
        controlEmpleados control = new controlEmpleados();
        control.crearPDF();
    }//GEN-LAST:event_btn_pdfActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        if (rol.equals("1")) {
            int fila = this.jTable1.getSelectedRow();
            lbl_codigo.setText((String) jTable1.getValueAt(fila, 0));
            lbl_empresa.setText((String) jTable1.getValueAt(fila, 1));
            box_tipoDoc.setSelectedItem(jTable1.getValueAt(fila, 2));
            txt_numDocumento.setText((String) jTable1.getValueAt(fila, 3));
            txt_nombre.setText((String) jTable1.getValueAt(fila, 4));
            box_genero.setSelectedItem(jTable1.getValueAt(fila, 5));
            txt_correo.setText((String) jTable1.getValueAt(fila, 6));
        } else {
            alertaInfo alerta = new alertaInfo("No tiene asignado el rol de \nadministrador.");
            alerta.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txt_numDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numDocumentoKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_numDocumentoKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        if (!Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed
        controlEmpleados control = new controlEmpleados();
        control.crearXLS();
    }//GEN-LAST:event_btn_excelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaEmpleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaEmpleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaEmpleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaEmpleados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String rol = null;
                new vistaEmpleados(rol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_genero;
    private javax.swing.JComboBox<String> box_tipoDoc;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_crearEmpleado;
    private javax.swing.JButton btn_excel;
    private javax.swing.JButton btn_pdf;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_empresa;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numDocumento;
    // End of variables declaration//GEN-END:variables

    private void llenarVista() {

        controlEmpleados control = new controlEmpleados();
        lbl_codigo.setText(control.contar());
        lbl_empresa.setText(control.empresa());

        box_tipoDoc.removeAllItems();
        List<modeloDocumentos> docTipos = control.tipoDoc();
        for (int i = 0; i < docTipos.size(); i++) {
            box_tipoDoc.addItem(docTipos.get(i).getTipo());
        }

        txt_numDocumento.setText("");
        txt_nombre.setText("");
        txt_correo.setText("");
    }

    private void cargarTabla(String buscar) {

        controlEmpleados control = new controlEmpleados();
        List<modeloEmpleados> empleados = control.Consultar(buscar);
        DefaultTableModel tabla = new DefaultTableModel();
        this.jTable1.setModel(tabla);

        tabla.addColumn("Id");
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Empresa");
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Tipo Documento");
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        tabla.addColumn("Documento");
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        tabla.addColumn("Nombre");
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(4).setResizable(false);

        tabla.addColumn("Genero");
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(5).setResizable(false);

        tabla.addColumn("Correo");
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(6).setResizable(false);

        for (modeloEmpleados empleado : empleados) {
            Object[] fila = new Object[7];
            fila[0] = empleado.getId();
            fila[1] = empleado.getEmpresa();
            fila[2] = empleado.getTipoDoc();
            fila[3] = empleado.getDocumento();
            fila[4] = empleado.getNombre();
            if (empleado.getGenero().equals("M")) {
                fila[5] = "Masculino";

            } else {
                fila[5] = "Femenino";
            }
            fila[6] = empleado.getCorreo();
            tabla.addRow(fila);
        }

    }

    private boolean verificarCorreo(String correo) {

        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\\\\\+]+(\\.[\\w\\\\]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);
        if (mat.find()) {
            return true;
        } else {
            return false;
        }
    }

}
