/*
SGI - Sistema Gestion de Inventarios 
Vista Entradas
 */
package Vistas;

import Alertas.vistas.alertaInfo;
import Controladores.controlEntradas;
import Controladores.controlItems;
import Modelos.modeloEntradas;
import Modelos.modeloItems;
import java.awt.MouseInfo;
import java.awt.Point;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Coronado
 */
public class vistaEntradas extends javax.swing.JFrame {

    /**
     * Creates new form vistaEntradas
     */
    private int x;
    private int y;
    private String buscar = "";
    private String rol;
    List<modeloEntradas> listaEntradas = new ArrayList<modeloEntradas>();

    public vistaEntradas(String usuario, String rol) {
        this.setUndecorated(true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        setSize(1300, 680);
        this.setLocationRelativeTo(null);
        llenarVista(usuario);
        cargarTabla(buscar);
        this.rol = rol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_items = new javax.swing.JTable();
        txt_codigo = new javax.swing.JTextField();
        txt_item = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        btn_anadirItem = new javax.swing.JButton();
        lbl_entrada = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_entradas = new javax.swing.JTable();
        btn_crearEntrada = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        btn_excel = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entradas");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1300, 680));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        txt_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_buscar.setBorder(null);
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        getContentPane().add(txt_buscar);
        txt_buscar.setBounds(176, 227, 170, 30);

        tbl_items = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Item", "Descripcion", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_items.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_items.setFocusable(false);
        tbl_items.setRowHeight(25);
        tbl_items.setSelectionBackground(new java.awt.Color(167, 125, 234));
        tbl_items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_itemsMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_items);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(40, 280, 320, 126);

        txt_codigo.setEditable(false);
        txt_codigo.setBackground(new java.awt.Color(255, 255, 255));
        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_codigo.setBorder(null);
        getContentPane().add(txt_codigo);
        txt_codigo.setBounds(176, 432, 170, 30);

        txt_item.setEditable(false);
        txt_item.setBackground(new java.awt.Color(255, 255, 255));
        txt_item.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_item.setBorder(null);
        getContentPane().add(txt_item);
        txt_item.setBounds(176, 483, 170, 30);

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cantidad.setBorder(null);
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cantidad);
        txt_cantidad.setBounds(176, 535, 170, 30);

        btn_anadirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entradas/btnAddItem1.png"))); // NOI18N
        btn_anadirItem.setBorder(null);
        btn_anadirItem.setBorderPainted(false);
        btn_anadirItem.setContentAreaFilled(false);
        btn_anadirItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_anadirItem.setFocusPainted(false);
        btn_anadirItem.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entradas/btnAddItem2.png"))); // NOI18N
        btn_anadirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirItemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_anadirItem);
        btn_anadirItem.setBounds(60, 580, 270, 43);

        lbl_entrada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_entrada);
        lbl_entrada.setBounds(525, 58, 170, 30);

        lbl_fecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_fecha);
        lbl_fecha.setBounds(800, 58, 170, 30);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_usuario);
        lbl_usuario.setBounds(1093, 58, 170, 30);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbl_entradas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbl_entradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Item", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_entradas.setComponentPopupMenu(jPopupMenu1);
        tbl_entradas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_entradas.setFocusable(false);
        tbl_entradas.setRowHeight(25);
        tbl_entradas.setSelectionBackground(new java.awt.Color(167, 125, 234));
        jScrollPane2.setViewportView(tbl_entradas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(420, 110, 855, 450);

        btn_crearEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entradas/btnCrearEntrada1.png"))); // NOI18N
        btn_crearEntrada.setBorder(null);
        btn_crearEntrada.setBorderPainted(false);
        btn_crearEntrada.setContentAreaFilled(false);
        btn_crearEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_crearEntrada.setFocusPainted(false);
        btn_crearEntrada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entradas/btnCrearEntrada2.png"))); // NOI18N
        btn_crearEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crearEntrada);
        btn_crearEntrada.setBounds(1008, 580, 270, 43);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(1270, 0, 30, 30);

        btn_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL1.png"))); // NOI18N
        btn_excel.setBorder(null);
        btn_excel.setBorderPainted(false);
        btn_excel.setContentAreaFilled(false);
        btn_excel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excel.setFocusPainted(false);
        btn_excel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL2.png"))); // NOI18N
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excel);
        btn_excel.setBounds(420, 564, 160, 70);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entradas/fondoEntradas.png"))); // NOI18N
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 1300, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed

        dispose();

    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_anadirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirItemActionPerformed

        String id = txt_codigo.getText();
        String item = txt_item.getText();
        String cantidad = txt_cantidad.getText();
        String usuario = lbl_usuario.getText();

        int fila = this.tbl_items.getSelectedRow();
        String disponible = (String) tbl_items.getValueAt(fila, 3);

        if (Integer.parseInt(cantidad) <= 0) {
            alertaInfo alerta = new alertaInfo("Verifique los datos \n"
                    + "la entrada no puede ser 0");
            alerta.setVisible(true);
        } else {
            modeloEntradas entradas = new modeloEntradas(id, item, cantidad);
            listaEntradas.add(entradas);

            cargarTablaEntradas();
            llenarVista(usuario);
        }

    }//GEN-LAST:event_btn_anadirItemActionPerformed

    private void btn_crearEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearEntradaActionPerformed

        controlEntradas control = new controlEntradas();
        modeloEntradas modelo = new modeloEntradas();

        control.crearDocumentoEntrada(lbl_entrada.getText(), lbl_usuario.getText());
        control.crearEntradas(lbl_entrada.getText(), listaEntradas);
        control.crearPDF(lbl_entrada.getText(), lbl_usuario.getText(), listaEntradas);
        listaEntradas.clear();
        listaEntradas.removeAll(listaEntradas);
        llenarVista(lbl_usuario.getText());
        cargarTabla(buscar);
        modelo = null;
        System.gc();
        cargarTablaEntradas();

    }//GEN-LAST:event_btn_crearEntradaActionPerformed

    private void tbl_itemsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_itemsMouseReleased

        int fila = this.tbl_items.getSelectedRow();
        txt_codigo.setText((String) tbl_items.getValueAt(fila, 0));
        txt_item.setText((String) tbl_items.getValueAt(fila, 1));

    }//GEN-LAST:event_tbl_itemsMouseReleased

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased

        buscar = txt_buscar.getText();
        cargarTabla(buscar);

    }//GEN-LAST:event_txt_buscarKeyReleased

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped

        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        listaEntradas.remove(tbl_entradas.getSelectedRow());
        cargarTablaEntradas();


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed

        controlEntradas control = new controlEntradas();
        control.crearXLS();

    }//GEN-LAST:event_btn_excelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String usuario = null;
                String rol = null;
                new vistaEntradas(usuario, rol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anadirItem;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_crearEntrada;
    private javax.swing.JButton btn_excel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_entrada;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable tbl_entradas;
    private javax.swing.JTable tbl_items;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_item;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla(String buscar) {

        controlItems control = new controlItems();
        List<modeloItems> items = control.Consultar(buscar);
        DefaultTableModel tabla = new DefaultTableModel();
        this.tbl_items.setModel(tabla);

        tabla.addColumn("Id");
        tbl_items.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbl_items.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Item");
        tbl_items.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_items.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Descripcion");
        tbl_items.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbl_items.getColumnModel().getColumn(2).setResizable(false);

        tabla.addColumn("Disponible");
        tbl_items.getColumnModel().getColumn(3).setPreferredWidth(30);
        tbl_items.getColumnModel().getColumn(3).setResizable(false);

        for (modeloItems item : items) {
            Object[] fila = new Object[4];
            fila[0] = item.getId();
            fila[1] = item.getNombre();
            fila[2] = item.getDescripcion();
            fila[3] = item.getDisponible();
            tabla.addRow(fila);
        }
    }

    private void llenarVista(String usuario) {

        controlEntradas control = new controlEntradas();
        lbl_entrada.setText(control.contar());

        DateTimeFormatter fecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        lbl_fecha.setText(fecha.format(LocalDateTime.now()));

        lbl_usuario.setText(usuario);
        txt_codigo.setText("");
        txt_item.setText("");
        txt_buscar.setText("");
        txt_cantidad.setText("0");

    }

    private void cargarTablaEntradas() {

        DefaultTableModel tabla = new DefaultTableModel();
        this.tbl_entradas.setModel(tabla);

        tabla.addColumn("Id");
        tbl_entradas.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbl_entradas.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Item");
        tbl_entradas.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_entradas.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Cantidad");
        tbl_entradas.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbl_entradas.getColumnModel().getColumn(2).setResizable(false);

        for (modeloEntradas entrada : listaEntradas) {
            Object[] fila = new Object[3];
            fila[0] = entrada.getId();
            fila[1] = entrada.getInventario();
            fila[2] = entrada.getCantidad();
            tabla.addRow(fila);
        }
    }
}
