/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Alertas.vistas.alertaInfo;
import Controladores.controlUsuarios;
import Controladores.controlRoles;
import Modelos.modeloEmpleados;
import Modelos.modeloRoles;
import Modelos.modeloUsuarios;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Coronado
 */
public class vistaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form vistaUsuarios
     */
    private int x;
    private int y;
    private String buscar = "";
    private String rol;

    public vistaUsuarios(String rol) {
        this.setUndecorated(true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        setSize(1300, 680);
        this.setLocationRelativeTo(null);
        llenarVista();
        cargarTabla(buscar);
        this.rol = rol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        lbl_codigo = new javax.swing.JLabel();
        box_empleado = new javax.swing.JComboBox<>();
        box_rol = new javax.swing.JComboBox<>();
        txt_usuario = new javax.swing.JTextField();
        txt_contrasena = new javax.swing.JPasswordField();
        btn_crearUsuario = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_pdf = new javax.swing.JButton();
        btn_excel = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        jMenuItem1.setText("Editar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1300, 680));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_codigo);
        lbl_codigo.setBounds(176, 215, 170, 30);

        box_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(box_empleado);
        box_empleado.setBounds(166, 275, 185, 30);

        box_rol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        box_rol.setToolTipText("");
        getContentPane().add(box_rol);
        box_rol.setBounds(166, 335, 185, 30);

        txt_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_usuario.setBorder(null);
        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(176, 400, 170, 30);

        txt_contrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_contrasena.setBorder(null);
        getContentPane().add(txt_contrasena);
        txt_contrasena.setBounds(176, 462, 170, 30);

        btn_crearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios/botonCrear1.png"))); // NOI18N
        btn_crearUsuario.setBorder(null);
        btn_crearUsuario.setBorderPainted(false);
        btn_crearUsuario.setContentAreaFilled(false);
        btn_crearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_crearUsuario.setFocusPainted(false);
        btn_crearUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios/botonCrear2.png"))); // NOI18N
        btn_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crearUsuario);
        btn_crearUsuario.setBounds(60, 580, 270, 43);

        txt_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_buscar.setBorder(null);
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        getContentPane().add(txt_buscar);
        txt_buscar.setBounds(522, 57, 180, 30);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Empleado", "Usuario", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(167, 125, 234));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 100, 850, 450);

        btn_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/botonPDF1.png"))); // NOI18N
        btn_pdf.setBorder(null);
        btn_pdf.setBorderPainted(false);
        btn_pdf.setContentAreaFilled(false);
        btn_pdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pdf.setFocusPainted(false);
        btn_pdf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/botonPDF2.png"))); // NOI18N
        btn_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdfActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pdf);
        btn_pdf.setBounds(420, 560, 150, 70);

        btn_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL1.png"))); // NOI18N
        btn_excel.setBorder(null);
        btn_excel.setBorderPainted(false);
        btn_excel.setContentAreaFilled(false);
        btn_excel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excel.setFocusPainted(false);
        btn_excel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes/btn_EXCEL2.png"))); // NOI18N
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excel);
        btn_excel.setBounds(570, 564, 160, 70);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar/botonCerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(1270, 0, 30, 30);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios/fondoUsuarios.png"))); // NOI18N
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 1300, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdfActionPerformed
        controlUsuarios control = new controlUsuarios();
        control.crearPDF();
    }//GEN-LAST:event_btn_pdfActionPerformed

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed
        controlUsuarios control = new controlUsuarios();
        control.crearXLS();
    }//GEN-LAST:event_btn_excelActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        buscar = txt_buscar.getText();
        cargarTabla(buscar);
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void btn_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearUsuarioActionPerformed

        String id = lbl_codigo.getText();
        String empresa = "1";
        String empleado = (String) box_empleado.getSelectedItem();
        String rol = (String) box_rol.getSelectedItem();
        String usuario = txt_usuario.getText();
        String contrasena = new String(txt_contrasena.getPassword());
        if (usuario.equals("") && contrasena.equals("")) {
            alertaInfo alerta = new alertaInfo("Por favor verifique los datos.");
            alerta.setVisible(true);
        } else {
            modeloUsuarios modelo = new modeloUsuarios(id, empleado, rol, usuario, contrasena);
            controlUsuarios control = new controlUsuarios();
            if (control.crearUsuario(modelo)) {
                txt_usuario.setText("");
                txt_contrasena.setText("");
            }

        }
        llenarVista();
        cargarTabla(buscar);

    }//GEN-LAST:event_btn_crearUsuarioActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);

    }//GEN-LAST:event_formMouseDragged

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed

        dispose();

    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        if (rol.equals("1")) {
            int fila = this.jTable1.getSelectedRow();
            lbl_codigo.setText((String) jTable1.getValueAt(fila, 0));
            box_empleado.setSelectedItem(jTable1.getValueAt(fila, 1));
            txt_usuario.setText((String) jTable1.getValueAt(fila, 2));
            box_rol.setSelectedItem(jTable1.getValueAt(fila, 3));
        } else {
            alertaInfo alerta = new alertaInfo("No tiene asignado el rol de \nadministrador.");
            alerta.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txt_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyTyped

        if (!Character.isDigit(evt.getKeyChar()) && !Character.isLetter(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_txt_usuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String rol = null;
                new vistaUsuarios(rol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_empleado;
    private javax.swing.JComboBox<String> box_rol;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_crearUsuario;
    private javax.swing.JButton btn_excel;
    private javax.swing.JButton btn_pdf;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

    private void llenarVista() {

        controlUsuarios controlU = new controlUsuarios();
        lbl_codigo.setText(controlU.contar());

        List<modeloEmpleados> empleados = controlU.empleados();
        box_empleado.removeAllItems();
        for (int i = 0; i < empleados.size(); i++) {
            box_empleado.addItem(empleados.get(i).getNombre());
        }

        controlRoles controlR = new controlRoles();
        List<modeloRoles> roles = controlR.roles();
        box_rol.removeAllItems();
        for (int i = 0; i < roles.size(); i++) {
            box_rol.addItem(roles.get(i).getNombre());
        }

        txt_usuario.setText("");
        txt_contrasena.setText("");
    }

    private void cargarTabla(String buscar) {

        controlUsuarios control = new controlUsuarios();
        List<modeloUsuarios> usuarios = control.Consultar(buscar);
        DefaultTableModel tabla = new DefaultTableModel();
        this.jTable1.setModel(tabla);

        tabla.addColumn("Id");
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        tabla.addColumn("Empleado");
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(1).setResizable(false);

        tabla.addColumn("Usuario");
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        tabla.addColumn("Rol");
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        for (modeloUsuarios usuario : usuarios) {
            Object[] fila = new Object[4];
            fila[0] = usuario.getId();
            fila[1] = usuario.getEmp();
            fila[2] = usuario.getUsuario();
            fila[3] = usuario.getRol();
            tabla.addRow(fila);
        }

    }

}
