/*
SGI - Sistema Gestion de Inventarios 
Vista Login
 */
package Vistas;

import java.awt.MouseInfo;
import java.awt.Point;
import Controladores.controlLogin;
import Modelos.modeloLogin;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Marco Coronado
 */
public class vistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form vistaLogin
     */
    private int x;
    private int y;
    
    public vistaLogin() {
        
        this.setUndecorated(true);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        setSize(850, 540);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_verpass = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        btn_cerrar = new javax.swing.JButton();
        btn_iniciarsersion = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGI Inventarios");
        setPreferredSize(new java.awt.Dimension(850, 540));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 540));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        btn_verpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login/botonPass.png"))); // NOI18N
        btn_verpass.setBorder(null);
        btn_verpass.setBorderPainted(false);
        btn_verpass.setContentAreaFilled(false);
        btn_verpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_verpass.setFocusPainted(false);
        btn_verpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_verpassMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_verpassMouseReleased(evt);
            }
        });
        getContentPane().add(btn_verpass);
        btn_verpass.setBounds(745, 348, 30, 20);

        txt_pass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_pass.setBorder(null);
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passKeyReleased(evt);
            }
        });
        getContentPane().add(txt_pass);
        txt_pass.setBounds(520, 348, 220, 20);

        txt_usuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_usuario.setBorder(null);
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(520, 260, 250, 20);

        btn_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login/botonCerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login/botonCerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(810, 0, 40, 40);

        btn_iniciarsersion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login/botonIniciar1.png"))); // NOI18N
        btn_iniciarsersion.setBorder(null);
        btn_iniciarsersion.setBorderPainted(false);
        btn_iniciarsersion.setContentAreaFilled(false);
        btn_iniciarsersion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iniciarsersion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login/botonIniciar2.png"))); // NOI18N
        btn_iniciarsersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarsersionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciarsersion);
        btn_iniciarsersion.setBounds(502, 400, 280, 40);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login/fondoLogin.png"))); // NOI18N
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 850, 540);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        
        System.exit(0);

    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_verpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verpassMousePressed
        
        txt_pass.setEchoChar((char) 0);

    }//GEN-LAST:event_btn_verpassMousePressed

    private void btn_verpassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verpassMouseReleased
        
        txt_pass.setEchoChar('*');

    }//GEN-LAST:event_btn_verpassMouseReleased

    private void btn_iniciarsersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarsersionActionPerformed
        String usuario = txt_usuario.getText();
        String contrasena = new String(txt_pass.getPassword());
        modeloLogin modelo = new modeloLogin(usuario, contrasena);
        controlLogin control = new controlLogin();
        if (control.iniciarSesion(modelo) == true) {
            vistaMenu ventanaMenu = new vistaMenu(usuario, modelo.getRol());
            ventanaMenu.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btn_iniciarsersionActionPerformed

    private void txt_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_iniciarsersion.doClick();
        }
    }//GEN-LAST:event_txt_passKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_iniciarsersion;
    private javax.swing.JButton btn_verpass;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

}
